name: Ejecutar transformación UTM

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GIS_USER: ${{ secrets.GIS_USER }}   # Aquí pasas el usuario guardado en secretos
  GIS_PASS: ${{ secrets.GIS_PASS }}   # Aquí pasas la contraseña guardada en secretos
  
jobs:
  transformacion:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        pip install arcgis pyproj pandas

    - name: Ejecutar el script de transformación
      run: |
        python transformar_coords.py
