name: Ejecutar Transformación UTM

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  ejecutar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install arcgis pyproj pandas

      - name: Ejecutar script
        env:
          ARCGIS_USERNAME: ${{ secrets.ARCGIS_USERNAME }}
          ARCGIS_PASSWORD: ${{ secrets.ARCGIS_PASSWORD }}
        run: |
          python transformar_coords.py
